# This file is a template, and might need editing before it works on your project.
image: python:latest

before_script:
  - python -V                                   # Print out python version for debugging

test:
  script:
  - pip install pytest
  - pip install pytest-cov
  - python setup.py install
  - python setup.py test
  - py.test --cov-report term --cov=groups --cov-branch tests

#  - pip install tox flake8  # you can also use tox
#  - tox -e py36,flake8

run:
  script:
  - python setup.py bdist_wheel
  # an alternative approach is to install and run:
  - pip install dist/*
  # run the command here
  artifacts:
    paths:
    - dist/*.whl
  only:
  - master
