image: python:latest

before_script:
  - python -V                                   # Print out python version for debugging

test:
  script:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-mock
  - python setup.py install
  - py.test --cov-report xml:cov_xml --cov=groups --cov-branch --cov-config .coveragerc

#  - pip install tox flake8  # you can also use tox
#  - tox -e py36,flake8

run:
  script:
  - python setup.py build
  - python setup.py install
  artifacts:
    paths:
    - dist/*.whl
  only:
  - master
